package com.andres.thefirst.books.entity;
// Generated 7/01/2016 12:29:13 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "books")
public class Book implements java.io.Serializable {

	private int id;
	private User user;
	private String book;
	private String author;
	private String editorial;
	private String isbn;
	private String resume;
	private String image;

	public Book() {
	}

	public Book(int id, User user, String book, String author, String editorial, String isbn) {
		this.id = id;
		this.user = user;
		this.book = book;
		this.author = author;
		this.editorial = editorial;
		this.isbn = isbn;
	}

	public Book(int id, User user, String book, String author, String editorial, String isbn, String resume,
			String image) {
		this.id = id;
		this.user = user;
		this.book = book;
		this.author = author;
		this.editorial = editorial;
		this.isbn = isbn;
		this.resume = resume;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "book", nullable = false, length = 100)
	public String getBook() {
		return this.book;
	}

	public void setBook(String book) {
		this.book = book;
	}

	@Column(name = "author", nullable = false, length = 200)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "editorial", nullable = false, length = 100)
	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	@Column(name = "isbn", nullable = false, length = 30)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "resume", length = 300)
	public String getResume() {
		return this.resume;
	}

	public void setResume(String resume) {
		this.resume = resume;
	}

	@Column(name = "image", length = 100)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
